api_token: "eyJ0eXBlIjoiSlcUIiwiYWxnIjoiSFM1MTIifQ.eyJqdGkiOiI2MjQwNDU0NyIsInJvbCI6IlJPTEVfUkVHSVNURVIiLCJpc3MiOiJPcGVuWExhYiIsImlhdCI6MTc3ODU1Njk0NiwiY2xpZW50SWQiOIJsa3pkeDU3bzZ6MjJqa3BxOXgydyIsInBob35lIjoiIiwib3BlbklkIjpudWxsLDJ1dWlkijoiNzI1ZWVkZTctYTVjZS01ZDE5LTkzMTAbYzc3MzAxMjNkYmQyIiwiZW1haWwiOiIiLCJleHAiOjE3ODYzMzI5NDZ7.4bHmvMEDTM-jHBpvFmSnWQteeBfU_Ir9lS0cFoW5a2WJrQT1xJ_D3ctb9XhvmwcilWoduY4Ts0-s6v_2cXrqzQ"

model_version: "pipeline"
is_ocr: true
enable_formula: true
enable_table: true
language: "ch"

max_pages: 200
max_size_mb: 200
split_size_mb: 150
batch_size: 50
poll_interval: 15

process_mode_threshold: 15
